In [1]:
import numpy as np


In [2]:
n1 = np.array([1,2,3,4])
print(n1)
print(type(n1))


[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
n1

array([1, 2, 3, 4])

In [4]:
x = []
dir(x)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [5]:
x = []
len(dir(x))

47

In [6]:
len(dir(n1))

165

In [7]:
n1.shape

(4,)

In [8]:
n2 = np.array([[1,2,3],[2,3,5]])
print(n2)
print(n2.shape)

[[1 2 3]
 [2 3 5]]
(2, 3)


creating matrix
- arange
- linescape
- random.rand
- random.randn
- random.randint
- eye
- ones
- zeroes

In [9]:
np.arange(-10,10, .2)



array([-1.00000000e+01, -9.80000000e+00, -9.60000000e+00, -9.40000000e+00,
       -9.20000000e+00, -9.00000000e+00, -8.80000000e+00, -8.60000000e+00,
       -8.40000000e+00, -8.20000000e+00, -8.00000000e+00, -7.80000000e+00,
       -7.60000000e+00, -7.40000000e+00, -7.20000000e+00, -7.00000000e+00,
       -6.80000000e+00, -6.60000000e+00, -6.40000000e+00, -6.20000000e+00,
       -6.00000000e+00, -5.80000000e+00, -5.60000000e+00, -5.40000000e+00,
       -5.20000000e+00, -5.00000000e+00, -4.80000000e+00, -4.60000000e+00,
       -4.40000000e+00, -4.20000000e+00, -4.00000000e+00, -3.80000000e+00,
       -3.60000000e+00, -3.40000000e+00, -3.20000000e+00, -3.00000000e+00,
       -2.80000000e+00, -2.60000000e+00, -2.40000000e+00, -2.20000000e+00,
       -2.00000000e+00, -1.80000000e+00, -1.60000000e+00, -1.40000000e+00,
       -1.20000000e+00, -1.00000000e+00, -8.00000000e-01, -6.00000000e-01,
       -4.00000000e-01, -2.00000000e-01, -3.55271368e-14,  2.00000000e-01,
        4.00000000e-01,  

In [10]:
x = np.arange(-10,10, .2)
x.shape

(100,)

In [11]:
y = np.linspace(1, 5, 25)
print(y)

[1.         1.16666667 1.33333333 1.5        1.66666667 1.83333333
 2.         2.16666667 2.33333333 2.5        2.66666667 2.83333333
 3.         3.16666667 3.33333333 3.5        3.66666667 3.83333333
 4.         4.16666667 4.33333333 4.5        4.66666667 4.83333333
 5.        ]


In [12]:
y.shape

(25,)

In [13]:
np.random.rand(10)

array([0.83975544, 0.14865363, 0.00526711, 0.2820886 , 0.59344128,
       0.17884178, 0.25177884, 0.51106462, 0.28917143, 0.38016222])

In [14]:
np.random.rand(3,3)

array([[0.97661578, 0.69002374, 0.59408727],
       [0.83090655, 0.76513416, 0.14602331],
       [0.94761866, 0.6599743 , 0.81035975]])

In [15]:
np.random.randn(10)

array([-1.11677241, -1.3314939 ,  0.97860256, -0.45159794, -1.96219485,
       -1.15435378, -1.61549075,  0.6058045 ,  0.5257987 ,  0.44666578])

In [16]:
np.random.randint(1, 5, (5,5))

array([[1, 4, 1, 1, 3],
       [2, 2, 4, 3, 2],
       [2, 1, 4, 1, 1],
       [2, 1, 1, 4, 1],
       [4, 2, 1, 2, 1]])

In [17]:
x = np.random.randint(1,11, (3,2))
y = np.random.randint(1,10, (3,2))
print(x)
print(y)

[[4 5]
 [1 6]
 [8 2]]
[[2 5]
 [5 3]
 [9 3]]


In [18]:
x + 5

array([[ 9, 10],
       [ 6, 11],
       [13,  7]])

In [19]:
x + y

array([[ 6, 10],
       [ 6,  9],
       [17,  5]])

In [20]:
x/y

array([[2.        , 1.        ],
       [0.2       , 2.        ],
       [0.88888889, 0.66666667]])

In [21]:
x * y

array([[ 8, 25],
       [ 5, 18],
       [72,  6]])

In [22]:
x.dot(y.T)

array([[33, 35, 51],
       [32, 23, 27],
       [26, 46, 78]])

In [23]:
np.sin(x)

array([[-0.7568025 , -0.95892427],
       [ 0.84147098, -0.2794155 ],
       [ 0.98935825,  0.90929743]])

In [24]:
print(x.sum())
print(x.mean())
print(x.std())

26
4.333333333333333
2.357022603955158


In [29]:
a= np.linspace(0, 5, 50)
print(a.shape)
a2 = a.reshape(10,5)
print(a2)
print(a2.shape)

(50,)
[[0.         0.10204082 0.20408163 0.30612245 0.40816327]
 [0.51020408 0.6122449  0.71428571 0.81632653 0.91836735]
 [1.02040816 1.12244898 1.2244898  1.32653061 1.42857143]
 [1.53061224 1.63265306 1.73469388 1.83673469 1.93877551]
 [2.04081633 2.14285714 2.24489796 2.34693878 2.44897959]
 [2.55102041 2.65306122 2.75510204 2.85714286 2.95918367]
 [3.06122449 3.16326531 3.26530612 3.36734694 3.46938776]
 [3.57142857 3.67346939 3.7755102  3.87755102 3.97959184]
 [4.08163265 4.18367347 4.28571429 4.3877551  4.48979592]
 [4.59183673 4.69387755 4.79591837 4.89795918 5.        ]]
(10, 5)


In [31]:
a2.reshape(5,5,2)

array([[[0.        , 0.10204082],
        [0.20408163, 0.30612245],
        [0.40816327, 0.51020408],
        [0.6122449 , 0.71428571],
        [0.81632653, 0.91836735]],

       [[1.02040816, 1.12244898],
        [1.2244898 , 1.32653061],
        [1.42857143, 1.53061224],
        [1.63265306, 1.73469388],
        [1.83673469, 1.93877551]],

       [[2.04081633, 2.14285714],
        [2.24489796, 2.34693878],
        [2.44897959, 2.55102041],
        [2.65306122, 2.75510204],
        [2.85714286, 2.95918367]],

       [[3.06122449, 3.16326531],
        [3.26530612, 3.36734694],
        [3.46938776, 3.57142857],
        [3.67346939, 3.7755102 ],
        [3.87755102, 3.97959184]],

       [[4.08163265, 4.18367347],
        [4.28571429, 4.3877551 ],
        [4.48979592, 4.59183673],
        [4.69387755, 4.79591837],
        [4.89795918, 5.        ]]])

In [37]:
m = np.random.randint(1,10,(10,10))
print(m)

[[3 3 5 7 1 3 9 8 6 6]
 [9 5 9 1 6 9 1 1 5 2]
 [2 5 3 8 9 2 9 9 9 4]
 [3 9 7 1 8 1 6 9 5 3]
 [9 9 9 1 3 5 5 1 2 1]
 [9 8 5 9 7 5 9 6 4 4]
 [2 9 8 2 3 6 2 1 5 8]
 [2 3 1 9 1 6 6 1 1 5]
 [7 6 4 9 6 8 6 3 9 4]
 [5 7 4 4 8 3 4 8 9 5]]


In [41]:
m[0, 0]
print(m[0, -1])
print(m[4, 3])
print(m[-1, 0])
print(m[-1,-1])


6
1
5
5


In [42]:
print(m[0])  # first row
print(m[1])   
print(m[-1])
print(m[:3])# first 3 rows


[3 3 5 7 1 3 9 8 6 6]
[9 5 9 1 6 9 1 1 5 2]
[5 7 4 4 8 3 4 8 9 5]
[[3 3 5 7 1 3 9 8 6 6]
 [9 5 9 1 6 9 1 1 5 2]
 [2 5 3 8 9 2 9 9 9 4]]


In [43]:
print(m[:,0])  #1st column
print(m[0:,-1])   # last column
print(m[:, :3])  # first 3 column
print(m[:, -3:])  # last 3 column

[3 9 2 3 9 9 2 2 7 5]
[6 2 4 3 1 4 8 5 4 5]
[[3 3 5]
 [9 5 9]
 [2 5 3]
 [3 9 7]
 [9 9 9]
 [9 8 5]
 [2 9 8]
 [2 3 1]
 [7 6 4]
 [5 7 4]]
[[8 6 6]
 [1 5 2]
 [9 9 4]
 [9 5 3]
 [1 2 1]
 [6 4 4]
 [1 5 8]
 [1 1 5]
 [3 9 4]
 [8 9 5]]


In [44]:
print(m[:, [0,2,3,5]])

[[3 5 7 3]
 [9 9 1 9]
 [2 3 8 2]
 [3 7 1 1]
 [9 9 1 5]
 [9 5 9 5]
 [2 8 2 6]
 [2 1 9 6]
 [7 4 9 8]
 [5 4 4 3]]


Filtering

In [47]:
m < 5 # boolean filter

array([[ True,  True, False, False,  True,  True, False, False, False,
        False],
       [False, False, False,  True, False, False,  True,  True, False,
         True],
       [ True, False,  True, False, False,  True, False, False, False,
         True],
       [ True, False, False,  True, False,  True, False, False, False,
         True],
       [False, False, False,  True,  True, False, False,  True,  True,
         True],
       [False, False, False, False, False, False, False, False,  True,
         True],
       [ True, False, False,  True,  True, False,  True,  True, False,
        False],
       [ True,  True,  True, False,  True, False, False,  True,  True,
        False],
       [False, False,  True, False, False, False, False,  True, False,
         True],
       [False, False,  True,  True, False,  True,  True, False, False,
        False]])

In [48]:
m[m<5]

array([3, 3, 1, 3, 1, 1, 1, 2, 2, 3, 2, 4, 3, 1, 1, 3, 1, 3, 1, 2, 1, 4,
       4, 2, 2, 3, 2, 1, 2, 3, 1, 1, 1, 1, 4, 3, 4, 4, 4, 3, 4])

In [49]:
m[m>3]

array([5, 7, 9, 8, 6, 6, 9, 5, 9, 6, 9, 5, 5, 8, 9, 9, 9, 9, 4, 9, 7, 8,
       6, 9, 5, 9, 9, 9, 5, 5, 9, 8, 5, 9, 7, 5, 9, 6, 4, 4, 9, 8, 6, 5,
       8, 9, 6, 6, 5, 7, 6, 4, 9, 6, 8, 6, 9, 4, 5, 7, 4, 4, 8, 4, 8, 9,
       5])

In [52]:
m[(m >= 3) & (m <= 6)]

array([3, 3, 5, 3, 6, 6, 5, 6, 5, 5, 3, 4, 3, 6, 5, 3, 3, 5, 5, 5, 5, 6,
       4, 4, 3, 6, 5, 3, 6, 6, 5, 6, 4, 6, 6, 3, 4, 5, 4, 4, 3, 4, 5])