In [1]:
import numpy as np


In [2]:
n1 = np.array([1,2,3,4])
print(n1)
print(type(n1))


[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
n1

array([1, 2, 3, 4])

In [4]:
x = []
dir(x)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [5]:
x = []
len(dir(x))

47

In [6]:
len(dir(n1))

165

In [7]:
n1.shape

(4,)

In [10]:
n2 = np.array([[1,2,3],[2,3,5]])
print(n2)
print(n2.shape)

[[1 2 3]
 [2 3 5]]
(2, 3)


creating matrix
- arange
- linescape
- random.rand
- random.randn
- random.randint
- eye
- ones
- zeroes

In [12]:
np.arange(-10,10, .2)



array([-1.00000000e+01, -9.80000000e+00, -9.60000000e+00, -9.40000000e+00,
       -9.20000000e+00, -9.00000000e+00, -8.80000000e+00, -8.60000000e+00,
       -8.40000000e+00, -8.20000000e+00, -8.00000000e+00, -7.80000000e+00,
       -7.60000000e+00, -7.40000000e+00, -7.20000000e+00, -7.00000000e+00,
       -6.80000000e+00, -6.60000000e+00, -6.40000000e+00, -6.20000000e+00,
       -6.00000000e+00, -5.80000000e+00, -5.60000000e+00, -5.40000000e+00,
       -5.20000000e+00, -5.00000000e+00, -4.80000000e+00, -4.60000000e+00,
       -4.40000000e+00, -4.20000000e+00, -4.00000000e+00, -3.80000000e+00,
       -3.60000000e+00, -3.40000000e+00, -3.20000000e+00, -3.00000000e+00,
       -2.80000000e+00, -2.60000000e+00, -2.40000000e+00, -2.20000000e+00,
       -2.00000000e+00, -1.80000000e+00, -1.60000000e+00, -1.40000000e+00,
       -1.20000000e+00, -1.00000000e+00, -8.00000000e-01, -6.00000000e-01,
       -4.00000000e-01, -2.00000000e-01, -3.55271368e-14,  2.00000000e-01,
        4.00000000e-01,  

In [17]:
x = np.arange(-10,10, .2)
x.shape

(100,)

In [18]:
y = np.linspace(1, 5, 25)
print(y)

[1.         1.16666667 1.33333333 1.5        1.66666667 1.83333333
 2.         2.16666667 2.33333333 2.5        2.66666667 2.83333333
 3.         3.16666667 3.33333333 3.5        3.66666667 3.83333333
 4.         4.16666667 4.33333333 4.5        4.66666667 4.83333333
 5.        ]


In [20]:
y.shape

(25,)

In [21]:
np.random.rand(10)

array([0.5712188 , 0.20417328, 0.32770328, 0.60979204, 0.5605121 ,
       0.95882895, 0.69930068, 0.50702177, 0.20038211, 0.86714278])

In [22]:
np.random.rand(3,3)

array([[0.6135253 , 0.67872711, 0.62599526],
       [0.43112267, 0.18222475, 0.79028906],
       [0.85710438, 0.29501065, 0.14237791]])

In [23]:
np.random.randn(10)

array([ 0.87192238, -2.06373387, -0.67516751,  0.1286649 ,  0.55988458,
        1.95303753,  0.58839356,  0.0285094 , -0.5079446 , -0.93869659])

In [25]:
np.random.randint(1, 5, (5,5))

array([[3, 3, 4, 1, 4],
       [3, 4, 3, 4, 4],
       [2, 1, 2, 1, 3],
       [2, 2, 4, 2, 4],
       [4, 1, 2, 3, 1]])

In [26]:
x = np.random.randint(1,11, (3,2))
y = np.random.randint(1,10, (3,2))
print(x)
print(y)

[[4 7]
 [1 3]
 [6 2]]
[[4 9]
 [9 8]
 [6 1]]


In [27]:
x + 5

array([[ 9, 12],
       [ 6,  8],
       [11,  7]])

In [28]:
x + y

array([[ 8, 16],
       [10, 11],
       [12,  3]])

In [1]:
x/y

NameError: name 'x' is not defined

In [31]:
x * y

array([[16, 63],
       [ 9, 24],
       [36,  2]])

In [36]:
x.dot(y.T)

array([[79, 92, 31],
       [31, 33,  9],
       [42, 70, 38]])

In [38]:
np.sin(x)

array([[-0.7568025 ,  0.6569866 ],
       [ 0.84147098,  0.14112001],
       [-0.2794155 ,  0.90929743]])

In [39]:
print(x.sum())
print(x.mean())
print(x.std())

23
3.8333333333333335
2.1147629234082532
